name: Install Tools
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update && \
        sudo apt-get install -y dotnet-sdk-8.0
      shell: bash
    - run: dotnet --version
      shell: bash
