name: "Terraform apply"
description: "Check for IAC directory and run terraform apply if exists"
runs:
  using: "composite"
  steps:
    - name: Terraform apply
      shell: bash
      run: |
        if [ -d "iac" ]; then
          cd iac
          echo "Terraform init"
          terraform init -reconfigure
          echo "Setting permissions..."
          chmod -R +x .terraform/providers/registry.terraform.io/hashicorp/
          echo "Terraform apply"
          terraform apply "terraform"
        else
          echo "Iac directory does not exist."
        fi
