name: Build

description: This action lists all enviornment variables

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path}}/build/initialize_environment.sh
      shell: bash