name: "Stage IAC Directory"
description: "Check for IAC directory and compress it if exists"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ -d "iac" ]; then
          echo "Staging iac directory."
          tar -czf iac.tgz iac
        else
          echo "Iac directory not found.
        fi
