name: "Terraform plan"
description: "Check for IAC directory and run terraform plan if exists"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ -d "iac" ]; then
          cd iac
          terraform init
          terraform validate
          terraform plan -out="terraform"
        else
          echo "Iac directory does not exist. Skipping step.
        fi
