name: Install Tools
runs:
  using: "composite"
  steps:
    - name: Install ASDF
      run: |
        git config --global advice.detachedHead false
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
        echo ". $HOME/.asdf/asdf.sh" >> $HOME/.bashrc
        echo ". $HOME/.asdf/completions/asdf.bash" >> $HOME/.bashrc
      shell: bash
    - name: Check installed version
      run: |
        asdf --version
      shell: bash
