name: Install terraform
runs:
  using: "composite"
  steps:
    - name: Install Terraform
      run: |
        . "$HOME/.asdf/asdf.sh"
        . "$HOME/.asdf/completions/asdf.bash"
        asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
        TERRAFORM_VERSION=$(asdf latest terraform)
        asdf install terraform $TERRAFORM_VERSION
        asdf local terraform $TERRAFORM_VERSION
      shell: bash
    - name: Check installed version
      run: |
        . "$HOME/.asdf/asdf.sh"
        . "$HOME/.asdf/completions/asdf.bash"
        terraform --version
      shell: bash
