name: CI

on:
  push:
    branches:
      - feature/workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/initialize_environment
      - uses: ./.github/actions/install_tools
      - uses: ./.github/actions/build
