name: CI

on:
  push:
    branches:
      - feature/workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize envrironment
        run: env
      - name: 
