name: CI

on:
  push:
    branches:
      - feature/workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/initialize_environment
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.3"
      - run: ls
